### ISSUE TITLE
dot2tex does not support xlabel

### ISSUE THREAD

**Issue by poizan42** [kjellmf/dot2tex#42]
This:

```
digraph G {
    node [shape="circle"];
    forcelabels=true;
    s1 [label="a", xlabel="s1"];
    s1 -> s2 -> s3;
}
```

Does not show the external label "s1" anywhere.

**Comment by MilesCranmer** [comment]
+1 - would also be nice to have an xlabel version of "texlbl"!

Thanks for making this package.
Cheers,
Miles
