### ISSUE TITLE
\input in tex doesn't work

### ISSUE THREAD

**Issue by noMICROSOFTbuhtz** [kjellmf/dot2tex#46]
I tried to use your `dot2tex` latex-environment with `\input`. But it doesn't
work. I am using a autogenerated dot-file. It comes from the
python-package `sadisplay` which visualize database structures.

The output told me to do this:

 `dot2tex --debug --figonly -ftikz -o x-dot2tex-fig1.tex x-dot2tex-fig1.dot`

Doesn't work because of

```
ERROR    Failed to create xdotdata. Is Graphviz installed?
ERROR    Failed to parse the input data. Is it a valid dot file?
Try to input xdot data directly. Example

    dot -Txdot file.dot | dot2tex > file.tex
```

Trying this to "input xdot data directly" works fine. So I can not see where the difference is.

I am using Ubuntu 14.04.3 LTS. I installed Python and Python3 packages "pyparser" and "graphviz" from PyPi.

[schema.zip](https://github.com/kjellmf/dot2tex/files/82028/schema.zip)

**Comment by fzalkow** [comment]
As far as I see, your file `x-dot2tex-fig1.dot` does not contain valid dot code. If it is autogenerated, you should rather report this issue to sadisplay?

**Comment by kjellmf** [comment]
I'm sorry, but dot2tex does not support including files using the {schema.dot} syntax. Try this syntax instead: https://dot2tex.readthedocs.io/en/latest/customization_guide.html#including-external-dot-files
