### ISSUE TITLE
Tikz format does not support node shape circle

### ISSUE THREAD

**Issue by kaimikael** [kjellmf/dot2tex#55]
When outputting in Tikz format, nodes specified with shape=circle are rendered as ellipses.
Ex:
digraph minimal {
  n [shape = circle, fixedsize = true, label = 11111]; 
}
through
dot2tex -ftikz minimal.dot
creates 
\begin{tikzpicture}[>=latex',line join=bevel,]
%%
\node (n) at (18.0bp,18.0bp) [draw,ellipse] {11111};
%
\end{tikzpicture}

**Comment by kjellmf** [comment]
Fixed in #60
