### ISSUE TITLE
Can we hope of having a Python3 version please?

### ISSUE THREAD

**Issue by Naereen** [kjellmf/dot2tex#56]

**Comment by Naereen** [comment]
In case you are interested, I starting to port it to Python 3.
My version is here, https://github.com/Naereen/dot2tex

**Comment by Naereen** [comment]
Hi @kjellmf.
I will not work more on my port to Python 3, but it could be useful to others if you try to merge it in your main version or at least take the ideas and make your version Py3K compatible?
Thanks in advance!

**Comment by Naereen** [comment]
@kjellmf any update?

**Comment by seba-1511** [comment]
@Naereen From your investigation, what seemed to be the problem ? What kind and amount of work do you think would be required to have Python 3 support ?

**Comment by Naereen** [comment]
Hi @seba-1511, well the few commits I did on my fork can tell you the problems I had to fix.
See https://github.com/Naereen/dot2tex/compare
It took me about max ~45min I think (it's been a few months), but it's definitely just a bunch of easy fixes.

I would very much like that someone with access to the dot2tex module on pypi do the change and update it there, right now my fork is useless as I won't upload it to pypi (can't do it, the name dot2tex is taken)

**Comment by seba-1511** [comment]
Thanks for the fast answer. Just to confirm, is your fork fully compatible with both Python 2 and 3 ? And without breaking changes ?

If so, can you create a pull request and maybe @kjellmf might be able to merge it and republish on pypi.

**Comment by Naereen** [comment]
Hi,
I will test again to check that I didn't break Py2 compatibility but I don't think so.
Will then fire a PR, alright.
(I was waiting for a feedback personally from @kjellmf as only he/she will be able to merge and republish)

**Comment by Naereen** [comment]
After a careful look at https://github.com/kjellmf/dot2tex/compare/master...Naereen:master, the only thing that could be broken on Py2 is when I removed `izip` and only used `zip`.
Except that, it looks perfectly compatible between the two versions.
Will try asap I have my other laptop :+1:

**Comment by Naereen** [comment]
I tried to fix the code for Py2 and now it broke the tests for Py3...
Don't have time to finish today, sorry

**Comment by Naereen** [comment]
From what I see, it's just a mess to have the code compliant for both Python 2 and 3... I just don't have time to this correctly, sorry.

My fork works perfectly on only Python 3, and [people shoudn't use Python 2 anymore](https://pythonclock.org), it's as simple as this...

**Comment by seba-1511** [comment]
Thanks for the update. 

I am unsure about the idea of breaking Python 2, a lot of people are still using it. I would like to take on this task, but don't have time to do it currently.

Maybe the simplest, most practical (but somewhat messy long term) solution is to publish your version on PyPI and name it `dot2tex3`. Thus, people could choose which version to install, each of them compatible with their respective Python version.

**Comment by Naereen** [comment]
Hi,
I don't think that's a nice solution, having two versions on PyPi is not recommended.
Not so much people are using dot2tex anyway, and I guess as soon as one sees that the PyPI version is not Py3 compatible, a quick lookup yields my fork so there is no need to hurry...

But sure if you can take care of this task, it would surely help. Good luck, whenever you have time.

**Comment by tscrim** [comment]
@Naereen I have picked up trying to do a compatibility of Python2/3 for dot2tex as I will need it for when [SageMath](https://www.sagemath.org) switches to Python3. Your branch has so far been quite helpful as I have been using that as a base and for ideas when I get confused. I am getting close to having the current test suite pass in Python2.

One important difference in my version: I am suggesting dropping support for anything below 2.7 in order to use things like `collections.OrderedDict`.

I separated out #65 as that is independent of the port.

**Comment by Naereen** [comment]
Hi @tscrim,
Dropping support for versions below 2.7 seems obviously okay for me, come it's been years :rofl:!
Please ask questions if you need, to finish the portage to Python3.

**Comment by tscrim** [comment]
Separated also is #66

**Comment by tscrim** [comment]
@Naereen Thank you. I will probably port over your unicode changes if that ends up being a problem. So far in my testing, that hasn't been an issue, but I haven't really tested that part yet (on Python3). I am plugging it into SageMath and running the testsuite through the mechanism there (as that is the downstream I care about), but I cannot seem to get past doing the import of dot2tex. That might be something on SageMath's end though...

**Comment by tscrim** [comment]
Okay, I was able to figure out the testing on Python3 was an issue in SageMath. Fixing that, I was able to go through and make the remaining changes necessary so that the tests pass (except for the one for #5). My changes are now on PR #68.

**Comment by kjellmf** [comment]
Closed by #68
