### ISSUE TITLE
make `setuptools` a strong dependency in `setup.py`

### ISSUE THREAD

**Issue by sandrotosi** [kjellmf/dot2tex#75]
when running the cli tool with the package built for python3 i get:

```
$ dot2tex --help
Traceback (most recent call last):
  File "/usr/bin/dot2tex", line 2, in <module>
    from .dot2tex import main
ImportError: attempted relative import with no known parent package
```

**Comment by sandrotosi** [comment]
this was due to `setuptools` being missing from the build chroot. since `distutils` is not able to generate a valid `console_script` i suggest to make `setup.py` strongly depend on `setuptools` (instead of falling back to `distutils` if unavailable)

**Comment by kjellmf** [comment]
Thanks for reporting this. Ideally it should work without any third party packages, but apparently it does not.
